name: Nix CI

on:
    push:
        pull_request:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repo
              uses: actions/checkout@v4

            - name: Install nix
              uses: cachix/install-nix-action@v25

            - name: Check flake
              run: nix flake check

            - name: Check nixOS config
              run: |
                echo "Warnings are normal and harmless"
                nix eval .#nixosConfigurations.nixos.config.system.build.toplevel 
