name: Nix CI

on:
  push:
  pull_request:

jobs:
  nix:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Flake metadata
        run: nix flake show

      - name: Flake check
        run: nix flake check

      - name: Lint (statix)
        run: nix run nixpkgs#statix check .

      - name: Dead code check (deadnix)
        run: nix run nixpkgs#deadnix .

      - name: Evaluate config
        run: nix eval --raw .#nixosConfigurations.nixos.config.system.build.toplevel

      - name: Build system
        run: nix build .#nixosConfigurations.nixos.config.system.build.toplevel
